---
title: "IdeasFinalProjectCKJS"
author: "Cande Torres, Kellie Stellmach, Jayden West, Shannon Dhor"
date: "11/5/2019"
output: 
  html_document:
keep_md: yes
---

__Link to our Group Repo__: https://github.com/jwest954/finalProjectCKJS

__Data set__: Endowment for Macalester and other 40 peer colleges from 2008 to 2017. This will be our primay set but we will defenilty complement it with supplementary data from the internet.

## Ideas for  our final project:

For our final project, we will be using data available online to analyze the trend of changes in the endowment possesed by colleges in the US. An endowment refers to the amount of money a college receives in donations. This endowment is then used for a variety of things like scholarships, upgrading facilities, hiring professors, and more.

We predict to find a an overall reduction trend in recent years according to the assumption that Liberal Art Education is less profitable compared to other emergent systems. 

(Souces: https://www.bloomberg.com/news/articles/2019-01-31/endowments-struggle-to-boost-returns-as-giving-to-students-rises)

With this data we propose some ideas on how to reach meaningful outcomes in our manipulation of the data:

* Look at how student enrollment relates to endowment over the years for both Macalester and peer colleges. Run statistical tests to measure the standard deviation from the average endowment for Liberal Art Colleges in the US to position Macalester and its peer colleges accordingly. 

* Seek for trends in the data that correlates with the US economic events of the time giving (ie: 2008 economic crisis and housing bubble) In other words, how did the economic and political situation of the country affected Liberal Art Colleges in terms of endowment and possibly other variables (retention rates, average financial aid, etc)

* Look at how the endowment compares to the general ranking for each college. Possibly analyse the correlation between both. 

* Highlight Regional difference in endowment patterns with cloropleth maps, comparing Colleges in the Midwest, West and East Coast. It is worth noticing that we will control for variables such as student body size, tuition cost, etc, to guarantee significant results. 





