---
title: "Map"
author: "Cande Torres"
date: "11/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)
library(devtools) 
library(openintro)
library(maps)
library(ggthemes) 
library(ggmap)
library(gplots) #new
library(RColorBrewer) #new
library(sf) #new
library(leaflet) #new
library(carData) 
```

```{r}
library(readxl)
map_data <- read_excel("/Users/cande/Desktop/Fall 2019/Intro to DataSC/FINALPROJECT/finalProjectCKJS/map_data/map-data.xlsx")
View(map_data)
```

```{r}
map_data_longer <- map_data %>% 
  select(-1*starts_with("20")) %>% 
  pivot_longer(cols = starts_with("R20"),
               names_to = "year", 
               values_to = "ranking") %>% 
  mutate(year= str_sub(year, start=2, end=5))
```

```{r}
map_data_lon <-map_data %>% 
  select(-1*starts_with("R20")) %>% 
  pivot_longer(cols=starts_with("20"),
               names_to = "year",
               values_to = "endowment")
```

```{r}
full_map_data<- map_data_longer %>% 
  full_join(map_data_lon, by=c("College", "year", "Region","lon", "lat", "State"))
```


Trying which map looks better here
```{r}
us2 <- get_stamenmap(
    bbox = c(left = -156.88, bottom = 13.50, right = -61.08, top = 62.27), 
    maptype = "toner",
    zoom = 4
)
```

```{r}
us <- get_stamenmap(
    bbox = c(left = -111.885, bottom = 25.205, right = -63.984, top = 50.903), 
    maptype = "toner",
    zoom = 4
)
```

```{r}
ggmap(us2)+
  geom_point(data = map_data,
             aes(x=lon, y=lat),
             color= "red", alpha=.7, size=.5)+
  labs(title = "Geographical location of Colleges in the US")

```
```{r}
states_map <- map_data("state")

geom_map(aes(map_id = state_name), map = states_map)+
geom_point(data = map_data,
             aes(x=lon, y=lat),
             color= "red", alpha=.7, size=.5)+
  labs(title = "Geographical location of Colleges in the US")

```

             
# Ignore everything before but the following map  
  
```{r}
leaflet(data = map_data) %>% 
  addTiles() %>% 
  addMarkers(lng = ~lon, lat = ~lat, label = ~College) 

#could addCircleMarkers, popupOption = TRUE add the College name in the legend, fillColor=~pal(ranking) I think I have to create a pallette like in the HW, provided user chose the year in the app before hand (not a slider but a pull down). 
```
  
  