---
title: "Wiki"
author: "Shannon Dohr"
date: "12/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r}
library(WikipediaR)
library(rvest)
library(tidyverse)
library(urltools)
```


```{r}

libarts_url <- "https://en.wikipedia.org/wiki/List_of_liberal_arts_colleges_in_the_United_States"

#get the names
libarts_colleges_step1 <-
  read_html(libarts_url) %>% 
  html_nodes("h2+ ul li") %>% 
  html_text()
```


```{r}
#get rid of a couple special cases
libarts_colleges_step2 <-
  libarts_colleges_step1[c(-23, -218, -1*(597:603))]

#create a dataset where the full_url variable is the wikipedia url for that college
libarts_tibble <- tibble(college = libarts_colleges_step2) %>% 
  separate(college, into = c("name"), sep = "\\(|\\[", extra = "drop") %>% 
  mutate(name_fix = str_replace_all(str_replace_all(str_trim(name), " ", "_"), ",", "_"),
         url_piece = url_encode(name_fix),
         url_piece_fix = str_replace_all(url_piece, "%e2%80%93", "-"),
         full_url = paste("https://en.wikipedia.org/wiki/", url_piece_fix, sep = ""))

```


